service: users-service

provider:
  name: aws
  runtime: nodejs22.x

functions:
  register:
    handler: src/index.handler
    events:
      - http:
          path: auth/register
          method: post
  login:
    handler: src/index.handler
    events:
      - http:
          path: auth/login
          method: post
  confirm:
    handler: src/index.handler
    events:
      - http:
          path: auth/confirm
          method: post
